version: 0.2

phases: 
  install:
    commands:
      - echo Installing Serverless...
      - npm install -g serverless@3.40.0
  pre_build:
    commands:
      - echo Install source NPM dependencies...
      - npm install --legacy-peer-deps
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with the Serverless Framework...
      - serverless deploy --verbose -v -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`
